### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by bcongdon** [acm-uiuc/groot-quotes-service#2]
Trying to get quotes integrated with `groot-voz`. Looks like all requests require a valid session (i.e. a valid netid/token).

It would be nice if we had a 'public' endpoint (like `groot-meme-service`) to poll random quotes.

**Comment by sameetandpotatoes** [comment]
Are you thinking `quotes/random` and `quotes/random/:netid`?

**Comment by bcongdon** [comment]
It's probably be nice to have both, although just `quotes/random` would be OK.

**Comment by narendasan** [comment]
I feel like getting a random quote is a bit dangerous considering its attributed to a person in the office

**Comment by tyler-thetyrant** [comment]
Some are also NSFW. Should not be fetched esp. during business hours and/or for the public

**Comment by bcongdon** [comment]
kk, yeah. Those concerns make sense.
